#pragma once

#define Key_Ampersand LSHIFT(Key_7)
#define Key_Asterisk LSHIFT(Key_8)
#define Key_At LSHIFT(Key_2)
#define Key_Caret LSHIFT(Key_6)
#define Key_Dollar LSHIFT(Key_4)
#define Key_DoubleQuote LSHIFT(Key_Quote)
#define Key_GreaterThan LSHIFT(Key_Period)
#define Key_LessThan LSHIFT(Key_Comma)
#define Key_Percent LSHIFT(Key_5)
#define Key_Plus LSHIFT(Key_Equals)
#define Key_Pound LSHIFT(Key_3)
#define Key_Question LSHIFT(Key_Slash)
#define Key_Tilde LSHIFT(Key_Backtick)
