#pragma once

#define Key_ADiaeresis RALT(Key_Q)
#define Key_ARing RALT(Key_W)
#define Key_Ampersand LSHIFT(Key_7)
#define Key_Asterisk LSHIFT(Key_8)
#define Key_At LSHIFT(Key_2)
#define Key_Caret LSHIFT(Key_6)
#define Key_Colon LSHIFT(Key_Semicolon)
#define Key_Dollar LSHIFT(Key_4)
#define Key_DoubleQuote LSHIFT(Key_Quote)
#define Key_EAcute RALT(Key_E)
#define Key_Exclamation LSHIFT(Key_1)
#define Key_GreaterThan LSHIFT(Key_Period)
#define Key_LeftDoubleQuoteMark LSHIFT(RALT(Key_LeftBracket))
#define Key_LeftSingleQuoteMark RALT(Key_9)
#define Key_LessThan LSHIFT(Key_Comma)
#define Key_ODiaeresis RALT(Key_P)
#define Key_Percent LSHIFT(Key_5)
#define Key_Plus LSHIFT(Key_Equals)
#define Key_Pound LSHIFT(Key_3)
#define Key_Question LSHIFT(Key_Slash)
#define Key_RightDoubleQuoteMark LSHIFT(RALT(Key_RightBracket))
#define Key_RightSingleQuoteMark RALT(Key_0)
#define Key_Tilde LSHIFT(Key_Backtick)

#define UNDECIDED XXX
